version: "3"

tasks:
  default:
    - task: help

  help:
    silent: true
    cmds:
      - task -l

  dev:
    desc: Develop build and run
    cmds:
      - nimble build && ./slackego run {{.CLI_ARGS}}

  package:
    desc: Packaging
    cmds:
      - nim c -d:ssl -d:release -d:quick --opt:size src/slackego.nim

  release:
    desc: |
      Build
          ∟ [Ex] task release VERSION=1.2.3
    cmds:
      - |
        sed -i -r 's/version       = \".+\"/version       = \"{{.VERSION}}\"/g' slackego.nimble
      - |
        sed -i -r 's/VERSION=v.+/VERSION=v{{.VERSION}}/g' install.sh
      - |
        sed -i -r 's/const VERSION = \".+\"/const VERSION = \"{{.VERSION}}\"/g' src/slackegopkg/args.nim
      - git add slackego.nimble install.sh src/slackegopkg/args.nim
      - git commit -m "📦Version {{.VERSION}}"
      - git tag v{{.VERSION}} -m v{{.VERSION}}
      - git push --tags
      - git push
    preconditions:
      - sh: "[ {{.VERSION}} != '' ]"
        msg: "VERSION is required."
